### ISSUE TITLE
Zen kernel swapping as hell

### ISSUE THREAD

**Issue by Harvie** [zen-kernel/zen-kernel#104]
Hello,
i use archlinux with SSD drive therefore i have vm.swappines set to 1. Lately when i boot to linux-zen (4.11.8, but it affected older versions also) it starts swapping so hard the mouse becomes unresponsive and i have no other choice than powercycling the machine. This happens like every second or third day of uptime, but there are even days when it happens 3 times in row. So it's safe to say that it happens once a day if i use RAM hard enough (=lots of browser tabs). This does not happen with other archlinux kernels.

**Comment by heftig** [comment]
Please try `sysctl vm.dirty_ratio=20 vm.dirty_background_ratio=10` to return to the default values.

**Comment by damentz** [comment]
@heftig that will only delay the behavior he's talking about

@Harvie what configuration are you running?  Certain configurations exacerbate this problem and make most systems unusable.  Specifically, the legacy single queue block system without cgroup support from the IO scheduler.

I'd recommend using blk-mq + bfq, , since that combination mostly avoid the symptoms you're talking about.  I've also read that disabling writeback throttling helps _a lot_, but I've hadn't noticed it to be a problem.  Try that if it's already enabled, since it may help with your system.

**Comment by Harvie** [comment]
@damentz i am using archlinux defaults

**Comment by timofonic** [comment]
@Harvie Any news? I use Archlinux too.

**Comment by damentz** [comment]
@timofonic As I recommended to @Harvie, try using Liquorix's configuration.

Closing out this issue since this the problem can been resolved, but requires changes to kernel configuration.  Use the Liquorix configuration as a reference if you're having issues.
