### ISSUE TITLE
USB flash devices are slow in general (usb-storage)

### ISSUE THREAD

**Issue by ilikenwf** [zen-kernel/zen-kernel#114]
I believe this is due to the use of relatime and probably the use of sync instead of flush on such devices. 

If you provide sync and noatime, USB transfer and unmount times drastically reduce.

Would this be something worth putting into the usb-storage driver, or perhaps a global setting somewhere in the config?

**Comment by damentz** [comment]
This should be set through a udev rule, but most (if not all), distributions don't enable syncing on USB drives.

Also, how would you determine you're using a fast USB 3.0 SSD drive versus a spinning disk versus a slow usb 2.0 commodity drive?

Closing this issue since this problem should be solved via enhanced or custom udev rules.
