### ISSUE TITLE
centos 5 style

### ISSUE THREAD

**Issue by csoyuncu** [zen-kernel/zen-kernel#118]
how can i config this kernel similiar centos 5 style kernel ? program when idle , cpu usage is %0

**Comment by damentz** [comment]
Hi csoyuncu,

You can take your CentOS kernel configuration and run `make oldconfig`, then use that configuration to build.  However, that's unlikely to get you a kernel build that works for you because CentOS 5's user space is so old.  I'd recommend upgrading your distribution something modern before using a modern kernel.

**Comment by csoyuncu** [comment]
Hello @damentz 
I want to update my servers to Centos 7, but the server program I am using has too many CPUs when idle. As an example, if I use CentOS 5, the server program uses 0% CPU, but when I install CentOS 7 (in any modern kernel) my server program uses 4-7% CPU. I want to solve this. Thank you.
