### ISSUE TITLE
Why the change

### ISSUE THREAD

**Issue by wisemagic777** [zen-kernel/zen-kernel#126]
I noticed that the makefile has changed from EXTRAVERSION = -zen to EXTRAVERSION = -zen1
Why is that?

**Comment by damentz** [comment]
This is actually a good point, the tag and the extraversion don't need to be the same.

If build systems that makes the binary kernel are configured correctly, they'll reference the tag when getting the kernel source or diff.  The package user can then trace back to the original PKGBUILD or distribution package source to find out where to get the original source code.

Also, since a human being is updating the tag (unless you're using a script to both tag and update the extraversion), there's a possibility that you'll tag a release with say, zen2 or zen3, but the zen1 extraversion will remain in the snapshot, leaving users who learn to depend on that to get the wrong idea of what version of the kernel they're using.

Jan, what are your thoughts?

**Comment by heftig** [comment]
I do use a script to change the `EXTRAVERSION`, commit and tag.

I like to follow upstream procedures where possible. Kernel.org handles their releases like this. The build system also provides a way to inject version suffixes (`localversion*` files). If I wanted to nail the kernel version to the `$pkgver` I would have to patch the Makefile during the build again.

**Comment by heftig** [comment]
And no, the `-zen1` consecutive suffixes refer to source releases (tags here), not package releases.

**Comment by damentz** [comment]
> You don't have to make tags every time you push to master.

Right, but lets say I merge the latest upstream updates, plus a fix for BFQ, as an example.  I'll push up a tag to indicate the snapshot used by the next Liquorix update, maybe including some release candidate patches that are not in master (so as not to keep rewriting history).  If you're taking some time off, the extraversion will stay at its previous value, despite changes being applied to master.

Because the extraversion contains an actual definitive version, it needs to bump after a significant update, otherwise it loses its meaning, and a '-zenN' release can cover a few to hundreds of commits.  However, you're tying the extraversion to the official zen tags for the Arch linux-zen package, so if I bump the extraversion, I need to also generate a tag to keep things in sync.  The tag of a '-zenN' release targets a single commit, while the extraversion in the master branch can cover any number of commits depending on how diligently it's kept up-to-date.

Do you understand what I'm saying here?  The sub-version of zen-kernel updates to the upstream Linux kernel doesn't belong in EXTRAVERSION.  Unless you can help me understand what you're seeing, lets keep the EXTRAVERSION value up to the package scripts and restore the EXTRAVERSION value back to "-zen".

> Can you elaborate what the problems were? Was the kernel used only for Gentoo at the time?

Yes, what happened is that Brandon, who went by "cheater-conrad" if I remember correctly, was tagging releases for his specific usage of Zen.  However, all the other members, including me, didn't care about his requirements for a tag, or when an update was worth tagging in the first place.  Tags from Brandon would lag significantly behind master, and we'd get lots of inquiries about bad behavior in the tag that was already fixed in master, or vice versa.

This is obviously far more exaggerated than the current situation, since a tag is typically cut per package update, and package updates almost always get released on every upstream kernel minor update.

> You can also push tags that aren't on branches. For example, for the Arch kernel, which gets its patches rebased for every release, I just push tags.

Ya, that's what I like about tagging currently with Liquorix.  Since I typically apply the latest release candidate patches at the time of tagging, I can continually reset X.YY/master-liquorix to X.YY/master, then re-apply the latest release candidates before cutting a tag, and you can still checkout historical tags and see all the commits that have already been rewritten in their original branch.
