### ISSUE TITLE
Liquorix 5.0.0-2.1 Freezes on Boot

### ISSUE THREAD

**Issue by Batcastle** [zen-kernel/zen-kernel#141]
I just installed Liquorix Kernel version 5.0.0-2.1 in Ubuntu 18.04 in a VM. Previously it was running the 4.20.0-13.1 release of Liquorix. Neither 5.0 nor that 4.20 kernel are able to boot. However, Version 4.20.0-12.1 boots just fine.

5.0 Freezes with this message on the screen in recovery mode:
`Disabling IRQ #9`

4.20.0-13.1 froze on `NetworkManager wait for connect service` at boot up.

I may be wrong in this being a kernel issue. From what I am seeing it may also be a `systemd` issue. But considering how 4.20.0-12.1 boots fine but everything after that didn't I am not so sure.

Also, I am not using `casper`, I am using `live-boot` instead due to some other bugs in the system. Just including that in case it matters.

**Comment by damentz** [comment]
Can you try booting with the additional kernel parameter, `nothreadirqs`?

**Comment by Batcastle** [comment]
That worked! Should I add this as a permanent change or is there something else I should change for whatever reason?

**Comment by damentz** [comment]
Well, I tried enabling `threadirqs` 8 years ago, and it had some of the same results.  Someone immediately reported that they couldn't boot a particular set of hardware and I needed to disable it on the next release.  This seems a lot better that it was just a VM, and no one else has reported any problems so far,  so I think I might remove `threadirqs` on my next release, but I'd like you to test one more thing.

Without `nothreadirqs` on your guest, can you try adding `intremap=no_x2apic_optout` to your kernel parameters on your host OS?  I'm curious if this changes the guest behavior and you can get your VMs to boot without `nothreadirqs`.  The only reason I suspect this might work is on all my machines running my kernel, both VirtualBox and VMware VMs work, so it might be something about the host rather than the guest.

**Comment by Batcastle** [comment]
Alright. I will give that a test as well and report back in a few. But, just as full disclosure, this VM is getting repackaged into an ISO and redistributed as a new OS (I said it was Ubuntu earlier because by and large it is. There are a few changes such as a more updated graphics stack, better gamepad support, and lower idle RAM usage. But, aside from those and your kernel, it's Ubuntu.)

If that isn't a concern. Then alright. I'm all for leaving it enabled if it helps with performance, security, or both. I just need to make sure the thing boots at all! XD

At any rate, I will report back with the changes you indicated shortly. Just thought you should be aware this is going to be redistributed as the default kernel in an OS.

**Comment by Batcastle** [comment]
Just tried your suggestion and it freezes at the exact same place. I checked host OS kernel logs and based on your edit it did work properly.

**Comment by damentz** [comment]
Gotcha, thanks for testing.  I'll revert the change once I get home and push out a new release.

**Comment by damentz** [comment]
Issue is fixed as of release: https://github.com/damentz/liquorix-package/releases/tag/5.0-2
