### ISSUE TITLE
[Feature request] Post patches applicable to current stable kernel

### ISSUE THREAD

**Issue by perfect7gentleman** [zen-kernel/zen-kernel#162]
i.e. post, for example,zen-5.5.1.patch applicable to kernel-5.5.1 (https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.5.1.tar.xz)

**Comment by damentz** [comment]
You mean our releases here?  The latest as of this post:

https://github.com/zen-kernel/zen-kernel/releases/tag/v5.5.1-zen1
https://github.com/zen-kernel/zen-kernel/releases/download/v5.5.1-zen1/v5.5.1-zen1.patch.xz

https://github.com/zen-kernel/zen-kernel/releases/tag/v5.5.1-lqx1
https://github.com/zen-kernel/zen-kernel/releases/download/v5.5.1-lqx1/v5.5.1-lqx1.patch.xz

**Comment by heftig** [comment]
They're asking for patches applying on top of A.B.C, not just A.B.

**Comment by damentz** [comment]
Ah, I see.  The reason we base our patches on the kernel major version is that all distribution packages are designed to use patches on top of the major version.

If you want a patch for the minor version, you can generate it yourself like so:

`git diff v5.5.1-zen1 v5.5.1`

That'll get you the differences.  We're not going to deploy these patches to our releases since they're redundant.  Not to mention, I'm not aware of any automated kernel build scripts that consume minor version patches.  Those typically have the minor version patch itself, followed by a large series of refreshed standalone patch files (Debian kernel packages comes to mind).  But those packages are carefully maintained with every patch in the series refreshed and carefully updated so as not to break the package build, a time consuming process.
