### ISSUE TITLE
Which CPU process scheduler is used by default: CFS or MuQSS?

### ISSUE THREAD

**Issue by corecontingency** [zen-kernel/zen-kernel#165]
I am trying to figure out what exactly is changed in the zen-kernel vs base linux, so I took a look at liquorix.net (according to the explanation in [#30](https://liquorix.net/#features), zen-kernel and liquorix are the same). I noticed that Zen Interactive tuning changes this:

```
--- CPU Scheduler (CFS) --------------------------------

Scheduling latency.............:   6    ->   3    ms
Minimal granularity............:   0.75 ->   0.3  ms
Wakeup granularity.............:   1    ->   0.5  ms
CPU migration cost.............:   0.5  ->   0.25 ms
Bandwidth slice size...........:   5    ->   3    ms

--- CPU Scheduler (MuQSS) ------------------------------

Scheduling interval............:   6    ->   2    ms
ISO task max realtime use......:  70 %  ->  25 %
```
I thought that you could only be using one CPU process scheduler at a time, so which scheduler is used by default? If MuQSS is the default scheduler, then why would CFS settings be tuned by this patchset if it is not in use, and vice-versa? Is there some config file I can edit to change the default scheduler from one to the other with zen-kernel installed?

Thanks.

**Comment by heftig** [comment]
The ZEN kernel I build uses CFS. The Liquorix kernel @damentz build uses MuQSS. Kernels built by others using our sources could use either, but never both.

**Comment by damentz** [comment]
Yup, and another disclaimer, @heftig 's build of Zen is configured more similarly to stock Arch.  I could be wrong here though, @heftig can clear that up.  As for Liquorix, it also runs a stock-ish configuration (support as much hardware as possible), but there are many config options that are set that are more opinionated (like not building any IO scheduler besides BFQ, as an example).

I'll mark this as closed since it isn't technically an issue being worked on.  We'll still see notifications if you respond.

**Comment by guglovich** [comment]
@damentz Hello. What are the current settings for the scheduler? I would like to see it on the main page too. I always have to look online and it's not clear if the data on the Lqx website is up to date.
