### ISSUE TITLE
[Feature Request] Improve dm-crypt responsiveness in high IO situations.

### ISSUE THREAD

**Issue by igo95862** [zen-kernel/zen-kernel#166]
Recently I encountered desktop unresponsive behavior during high IO operations which I thought was not possible under linux-zen. I narrowed down the issue to dm-crypt by using iotop. 

From reading source code it seems like dm-crypt allocates only one queue to manage the encryption and decryption. This probably does not have any fairness in it so one process can grab entire crypt IO and starve all other processes. 

One queue gets initialized.
https://github.com/zen-kernel/zen-kernel/blob/5.5/master/drivers/md/dm-crypt.c#L2710 

Crypt config structure only has one queue: 
https://github.com/zen-kernel/zen-kernel/blob/5.5/master/drivers/md/dm-crypt.c#L133

Since zen kernel focuses on responsiveness I though this is a good place to report this issue. However, upstream might also be interested in this.

**Comment by damentz** [comment]
It seems that dm-crypt already encrypts and decrypts using multi-core, back from kernel 4.0:

http://lkml.iu.edu/hypermail/linux/kernel/1304.1/01458.html
https://www.phoronix.com/scan.php?page=news_item&px=MTM0NzQ

Also, just below the line you referenced, you can see code configuring kcryptd for the number of online CPUs:

```
	if (test_bit(DM_CRYPT_SAME_CPU, &cc->flags))
		cc->crypt_queue = alloc_workqueue("kcryptd/%s", WQ_CPU_INTENSIVE | WQ_MEM_RECLAIM,
						  1, devname);
	else
		cc->crypt_queue = alloc_workqueue("kcryptd/%s",
						  WQ_CPU_INTENSIVE | WQ_MEM_RECLAIM | WQ_UNBOUND,
						  num_online_cpus(), devname);
```

If the dm-crypt documentation, if you enable `same_cpu_crypt`, it'll restrict enc/decryption to the CPU that was handling IO:

```
same_cpu_crypt
    Perform encryption using the same cpu that IO was submitted on.
    The default is to use an unbound workqueue so that encryption work
    is automatically balanced between available CPUs.
```

https://www.kernel.org/doc/html/latest/admin-guide/device-mapper/dm-crypt.html

Are you saying that we also need to increase the number of IO queues?  I'd expect one IO queue per device.  We'd need some evidence that setting up multiple IO queues is beneficial for most systems.

**Comment by igo95862** [comment]
Its not about multi-core.

Its about fair queuing. 

Think about if we have bottleneck in CPU.

If one process has disproportionally more IO when it will take most of place in encryption/decryption queue and block smaller processes of chance being encrypted/decrypted.

This causes the desktop unresponsive behavior.

The issue is that dm-crypt sits on top of disks and by-passes any underlying scheduler. In order to make dm-crypt not cause unresponsive behavior it needs to implement some kind of fair queue mechanism there one process can't grab entire CPU and IO.

**Comment by damentz** [comment]
There shouldn't be a bottleneck in the CPU if all your cores are being used to encrypt/decrypt.  It's probably more that device mapper doesn't support elevators like bfq or deadline.  That means the real way to solve this is to get a good nvme drive that can handle tons of IOPS and cross your fingers it can do two things at the same time.

As far as adding more threads to the IO work queue, have you tried it yourself?  And are there patches in other projects that have tried this before?

**Comment by damentz** [comment]
Ok, so basically unless we get some existing work from someone else that shows modifying the number of IO queues help with dm-crypt, I'd rather not change this, especially since I don't use dm-crypt myself.

Now here's the answer you probably don't want.  If you want high performance and encryption, what you probably want is to enable encryption on the drive itself through your BIOS (if supported):
https://wiki.archlinux.org/index.php/Self-Encrypting_Drives and https://wiki.archlinux.org/index.php/Solid_state_drive#Security .  If you can get this to work, hopefully it's just a matter if typing in your password when the system turns on.

There are known exploits, like if your system is suspended and stolen, someone with the right technique can access the drive as long as it's never powered down.  There's also the potential for backdoors in the firmware of your BIOS/UEFI and/or drive itself  But otherwise, if you're casually encrypting your disk for peace of mind, it's probably good enough in the instance your system is stolen by someone just trying to get hardware or sell your system on the black market.

I think the big fail with dm-crypt is definitely the fact that there's no elevator.  For drives with low IOPS, there's no way to get good interactivity while using the drives for more than one thing at once.

I'll mark this as closed for now.  If you get some better data, maybe working patches from someone else's attempt to improve dm-crypt performance, we can take another look.
