### ISSUE TITLE
AMD Ryzen 5 2600, Linux Mint 19: weird load average, ksoftirqd seems to be a little restless

### ISSUE THREAD

**Issue by SoftwareGuy** [zen-kernel/zen-kernel#170]
Greetings,

I'm currently on `5.6.0-8.1-liquorix-amd64` and I've just noticed that when idle, my X570-based system seems to be... well, how to put it... like it's caffeinated. That said, when I look at top, I see ksoftirqd processes nibbling away at CPU usage (usually under 10% CPU usage as per top). When I've got things going on (ie. KVM guest running since I run Windows 10 inside it with GPU passthrough), those ksoftirqd processes drop back down to 0.3 - 1% CPU per process. Which is acceptable.

Now I understand these are kernel threads that are policing the interrupts and processing it as fast as it can judging from what I've read on the internet. Looking at `/proc/softirqs` seems to point at `TIMER` and `RCU` both quietly counting up. `TIMER` seems to be clicking up by 250 - I assume that's the scheduler frequency (ie. 250Hz). RCU also seems to be clicking up slowly.

Mint also started not responding on shutdown for some reason that I haven't diagnosed. Might be the 5.6 kernel being a little buggy. On Funtoo and a custom built `5.5.13-zen1` (not sure about -zen2?) kernel using the default settings extracted from Mint's kernel (the lqx one), this problem still exists, I see ksoftirqd sometimes spiking above 10% CPU.

So my question is - should I be concerned? Usually I would expect my idle load average to be below 1, but from what I've see on Mint, idle seemed to be around 2.5 - 3.0 load average.

**Comment by damentz** [comment]
Yep, it looks like you've spotted an anomaly caused by the way Liquorix is configured.  Due to time accounting issues on MuQSS, Liquorix is configured with a 250hz periodic tick rather than tickless idle.  To work around the coarseness of this low frequency tick, high resolution timers are used to schedule tasks instead of the 4ms jiffy.

Is your system downclocking the core frequencies when idle?  If so, what you're seeing is that the periodic tick is using a larger amount of CPU than usual.  Even on my systems I don't get nearly 10% CPU while idle from ksoftirqd, so it may be some other device on your system.

What does the output of powertop look like while idle?  I something else on your system generating interrupts besides the timer?

And as a side note, it looks like Con make some adjustments to how time is accounted for for MuQSS v199 per the diff in this commit: https://github.com/zen-kernel/zen-kernel/commit/d5ebb5eb .  This could mean that time accounting is more or less accurate.  It could also mean that tickless idle time accounting works again properly, but I haven't tested it.

**Comment by SoftwareGuy** [comment]
Ah crap - that’s the wrong button. I’ll get you those details ASAP (I’m still getting used to this Github Client on iOS, went to close the comment box but it closed the issue instead).

Thanks for your reply!

My CPU does underclock itself when idle. I think this is due to the on demand governor underclocking the CPU when idle instead of performance. I know the kernel is set to default to performance but something in Mint overrides it at boot, probably some systemd unit.

I will do powertop shortly and post my findings here.

**Comment by SoftwareGuy** [comment]
Okay, so I took a look in powertop with a rather idle load (ie. Funtoo with just GNOME Terminal loaded and it's usual background stuff) as you can see from the screenshot before:

![Screenshot from 2020-05-03 04-24-22](https://user-images.githubusercontent.com/1762115/80899516-53bebd80-8d54-11ea-88be-6861dcf5a183.png)

Since I haven't installed the frequency controlling packages yet, the CPU was set to performance mode (not ondemand). The clocks were at 3400Mhz when I checked during powertop was running. I am not sure how to interpret this, but it does seem the timer seems to be the most aggressive event generator.

**Comment by damentz** [comment]
Ah, well there it is.  The timer interrupt is using far more CPU time than it should, and it's firing more often.  Did you take this screenshot after letting powertop sample for a while?  In my experience, the first one or two snapshots of wakeups tend to be very inaccurate but calm down shortly afterwards.

I'll experiment re-enabling tickless idle, but more testing will be required to avoid another rehash of this issue: https://github.com/damentz/liquorix-package/issues/24.  Basically, enabling tickless idle affects the actual cpu accounting of running applications, and for this issue in particular, made it look like the CS GO server daemon was using many times more CPU than it really was.

**Comment by SoftwareGuy** [comment]
I think that screenshot was taken after 10 - 20 seconds of leaving powertop idle. It didn't show any data for around 5 seconds, and then it suddenly spat out a snapshot after that.

**Comment by damentz** [comment]
@SoftwareGuy you should be seeing 5.6.0-10.2 showing up soon in your updates, can you let me know how much this helps (if at all)?

This update also includes MuQSS v0.200, which came out after I had mentioned v0.199.  This fixes load averaging that you see in `top` and `uptime` and include the changes from v0.199 that track idle tasks differently (and hopefully more accurately).

Here's a full changelog in the update that's building now:
  * merge MuQSS v0.200
  * enable tickless idle
  * switch tick rate from 250hz to 1000hz
  * enable CGROUP options RDMA and PIDS
  * enable Pressure Stall Information (CONFIG_PSI), disabled by default
  * update version to 5.6.0-10.2

**Comment by SoftwareGuy** [comment]
Awesome. I'll take a look!

I just migrated to Funtoo and got rid of Mint (well, it's archived in a tarball on my backup drive). What I wanted to ask is for your releases, do you just use "make defconfig" or do you have a default config file you feed into the build system for Ubuntu/Debian-based systems? If you have that default config, is it available so I can load it when I "make menuconfig" in Funtoo? (I leave the defaults as is, but usually try to trim down a bit of stuff).

**Comment by damentz** [comment]
Liquorix uses a configuration that I've curated over a long time, and it's located deep in the debian package here: https://github.com/damentz/liquorix-package/blob/5.6/linux-liquorix/debian/config/kernelarch-x86/config-arch-64

When a new kernel comes out or a patch adds/removes options, I use `make oldconfig` to resolve outstanding issues that Kconfig needs answered.

You can look at the AUR package for Arch since it just takes the bits it needs to make the kernel itself and ignores any Debian specific items in the package: https://aur.archlinux.org/packages/linux-lqx/

**Comment by SoftwareGuy** [comment]
Brilliant. Thanks for that!

Also, I tested the latest kernel, and can confirm that when idle, the load average is now more sane. Not as high as before but from what I saw but less than 0.5 load average. I’ll check again this morning, but I did see a big drop in loadavg when I was on the good known 5.5.x kernel.

**Comment by SoftwareGuy** [comment]
Hmm, seems that powertop now triggers some warning from the kernel saying stack smashing was detected and the kernel terminated/aborted the process. This is building from your configuration file.

On the 5.5.x kernel I compiled it worked fine. Did something change in the configuration for 5.6? Other than this, everything is responding as normal, I see load averages that are much better than before, I'm pretty confident I can mark this as resolved.

**Comment by SoftwareGuy** [comment]
I'll close this for now. I'll keep an eye on the releases and I'll reopen if the regression/bug resurfaces, but thanks again for your help. I appreciate it. 

If you had a tip jar I'd gladly throw some coins your way. By far this is the most performance-oriented kernel I've used.

**Comment by damentz** [comment]
> Hmm, seems that powertop now triggers some warning from the kernel saying stack smashing was detected and the kernel terminated/aborted the process. This is building from your configuration file.
> 
> On the 5.5.x kernel I compiled it worked fine. Did something change in the configuration for 5.6 that could have broken powertop? Other than this, everything is responding as normal, I see load averages that are much better than before, I'm pretty confident I can mark this as resolved.

Hmm, the only thing I could find was this option I enabled, but it goes back to early 5.4 releases: https://github.com/damentz/liquorix-package/commit/fdce57e9bf0c76d965151969abbe6187c5ef099c

Perhaps it's some upstream change that added some inherent security to the kernel?  I know that I should probably turn some other security features but the last time I did that, the kernel oops'd immediately (https://github.com/damentz/liquorix-package/commit/e156466dc95674f11420246e15dac7d8c4d1237b).  So many things have changed since I disabled stack protection that it probably works again, I'll probably experiment and re-enable some more of these feature incrementally and hopefully nothing breaks.



> I'll close this for now. I'll keep an eye on the releases and I'll reopen if the regression/bug resurfaces, but thanks again for your help. I appreciate it.
> 
> If you had a tip jar I'd gladly throw some coins your way. By far this is the most performance-oriented kernel I've used.

Thanks!  That means a lot to me.

As for if what we solved here will regress, that's actually possible.  I currently have this issue open and it looks like we may need to revert back to periodic tick to resolve suspend issues if it's not an upstream bug: https://github.com/damentz/liquorix-package/issues/30

Also we had another issue where a particular system couldn't boot without `nosmt`: https://github.com/damentz/liquorix-package/issues/29

I can report these issues to Con, but he's already limiting the amount of time he spends working on MuQSS.  I'll let you know if I need to revert the changes I made for this issue.
