### ISSUE TITLE
Consider OpenRGB Support

### ISSUE THREAD

**Issue by bbedward** [zen-kernel/zen-kernel#174]
OpenRGB allows controlling LEDs on i2c devices, useful for controlling RGB such as asus aura, trident z, etc.

It requires an additional i2c driver for intel, and a small modification for piix4/AMD driver.

Reference:
https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/OpenRGB-Kernel-Patch

https://gitlab.com/CalcProgrammer1/OpenRGB

Would like to see this in zen+liquorix, would make it the easiest way to get support for this for users.

**Comment by damentz** [comment]
Added and merged to 5.6 and 5.7 master branches:
https://github.com/zen-kernel/zen-kernel/commit/e0639fec63c489fcf6a50a67b14fb06127b0aef3
https://github.com/zen-kernel/zen-kernel/commit/02821bd597ef4c6c49418f9513597a79393ad635

We'll look for an updated patch on every kernel release unless we're poked otherwise.

**Comment by bbedward** [comment]
Awesome, thanks. Will it make it to liquorix too?

**Comment by damentz** [comment]
@bbedward yep, a release is coming out as I post: https://github.com/damentz/liquorix-package/releases/tag/5.6-21

```
linux-liquorix (5.6-21)

  * merge 5.6.19
  * add OpenRGB support
  * enable CONFIG_I2C_NCT6775 for OpenRGB
  * enable CONFIG_CHECKPOINT_RESTORE
  * update version to 5.6.0-19.1

 -- Steven Barrett <steven@liquorix.net>  Wed, 17 Jun 2020 14:42:58 -0500
```
