### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by shrisha108** [zen-kernel/zen-kernel#179]
Hello, could someone quickly answer my question? Using zen kernel for few days now and interactivity during heavy tasks is much worth then stock kernel. It makes me wonder if I compile zen kernel properly. I just cloning git and use default config file from my system latest stock kernel. But I noticed you have the patch file separately for download, so may be I use unpatched kernel?
I'm on Fedora 32. Threadripper 3970x Titan RTX 64GB RAM. zen-kernel 5.7.19
Thank you.

**Comment by damentz** [comment]
The only official build of Zen Kernel that I'm aware of is @heftig's in Arch as `linux-zen`: https://www.archlinux.org/packages/extra/x86_64/linux-zen/

If you build your own kernel then all I can recommend is you use the configuration from the Arch package as your starting point.  I'm not familiar with Fedora enough to know if they configure the kernel for low latency.  By taking Fedora's configuration and compiling Zen Kernel without any changes, you're basically getting Fedora since we put most of our tweaks behind configurations.  To get the right behavior you need to at least enable CONFIG_ZEN_INTERACTIVE and enable hard preemption, but I recommend copying the Arch kernel config and working backwards to making Fedora work, not the other way around.

**Comment by shrisha108** [comment]
Thanks so much for your answer Steven. Yes zen interactive was enabled, but preemption was set as voluntary. So I changed to Preemptible Kernel and it is made a difference. At list interactivity now is on a level of stock kernel. Will take a look at archlinux  zen kernel config for further investigation.
Thanks again.
Appreciated.
