### ISSUE TITLE
Cannot compile AMD microcode support without Intel microcode support

### ISSUE THREAD

**Issue by JoshyPHP** [zen-kernel/zen-kernel#182]
I can't compile current HEAD 460a32f85e948210a8d564b11a6acb134ceba21e without `CONFIG_MICROCODE_INTEL` if  `CONFIG_MICROCODE_AMD` is enabled. It seems to originate from 7eaeff258d5dc4c9eb72b5969c009e6b416d273b which adds `force_ucode_load` to `arch/x86/kernel/cpu/microcode/intel.c` but not to `arch/x86/kernel/cpu/microcode/amd.c`. Enabling Intel microcode support fixes it.

Paging @ashok-raj to confirm.

```
ld: arch/x86/kernel/cpu/microcode/core.o: in function `reload_store':
core.c:(.text+0x3ab): undefined reference to `force_ucode_load'
ld: core.c:(.text+0x3e7): undefined reference to `force_ucode_load'
ld: arch/x86/kernel/cpu/microcode/core.o: in function `reload_store.cold':
core.c:(.text.unlikely+0x9e): undefined reference to `force_ucode_load'
ld: core.c:(.text.unlikely+0xbb): undefined reference to `force_ucode_load'
ld: core.c:(.text.unlikely+0xf8): undefined reference to `force_ucode_load'
```

**Comment by pr-delta** [comment]
Exact issue encountered. Enabling intel microcode fixes it.

**Comment by damentz** [comment]
The two patches from clearlinux that add support for force reloading microcode have been removed.  Even if we add support for forced reloading of microcode to AMD, I don't think anyone would realistically use it.

This feature must have been used for diagnostics internally at Intel, like if they're beta testing microcode and don't want to bump the revision number every iteration.  Not something you'll ever see a user with _signed_ microcode doing.

**Comment by sirlucjan** [comment]
@damentz

You should probably reverse it too:

https://github.com/zen-kernel/zen-kernel/commit/40191dbc009c68dedb015e5306b824a53e771232

**Comment by damentz** [comment]
@sirlucjan thanks, just reverted.

**Comment by ashok-raj** [comment]
I’m not familiar what Xen-kernel project is? Is it official zen or some other fork?

Looks like the problem is fixed and needs no further attention.

Cheers,
Ashok Raj

-- Sent from my iPhone

On Sep 28, 2020, at 8:06 AM, Steven Barrett <notifications@github.com> wrote:

﻿

@sirlucjan<https://github.com/sirlucjan> thanks, just reverted.

**Comment by damentz** [comment]
Hi @ashok-raj, the issue is that the clearlinux microcode patches make `CONFIG_MICROCODE_AMD` depend on `CONFIG_MICROCODE_INTEL`.  To fix this, the patches should make the AMD option depend on INTEL, or you should add the relevant `ifdefs` so that changes to Intel microcode doesn't impact AMD exclusive builds.

We reverted the patches in question since they're not something a regular user would use, but if you don't fix the patches upstream in clearlinux, you'll probably get more questions down the road about how the microcode patches create the build errors in the first post here: https://github.com/zen-kernel/zen-kernel/issues/182#issue-702358210
