### ISSUE TITLE
Why is linux-zen not coming with MuQSS scheduler?

### ISSUE THREAD

**Issue by mabod** [zen-kernel/zen-kernel#194]
On my search for the best kernel for me I compared linux-lqx and linux-zen. All information I found made me believe that both kernels are basically the same. 

On linux-liquorix github it says:

> Patches
> -------
> liquorix applies small changes and upstream backports to the kernel source.
> These are split up into separated patches addressing individual problems. 
> Each of the patch files contains a description and mentions the author. The 
> patches can be found at:
> https://github.com/zen-kernel/zen-kernel

(quote from: https://github.com/damentz/liquorix-package/tree/5.10/master/linux-liquorix/debian)

And this informational linux-zen issue https://github.com/zen-kernel/zen-kernel/issues/30 says:

> Please look at http://liquorix.net/ ; most points apply, since the code is the same.

But yet linux-lqx comes with MuQSS scheduler enabled and linux-zen is not. This is true for the 5.10.3 kernels I have compared. That is a fundamental difference which is nowhere described or explained. Why is MuQSS not part of linux-zen?

**Comment by heftig** [comment]
I've been generally unimpressed by the code quality (see all the fixups we pile on) and I prefer having cgroup scheduling available.

**Comment by mabod** [comment]
This is totally confusing. 

Liquorix is referring to the zen kernel for all the patches. But zen does not include the MuQSS patches. So where are the MuQSS patches for Liquorix then?

And on the other hand you answer in issue #30 the question about the benefits of the zen kernel with

> Please look at http://liquorix.net/ ; most points apply, since the code is the same.

This is all totally contradictory. And there is absolutly no transparency what you are actually doing with the kernel.

**Comment by heftig** [comment]
It does include the MuQSS patches. All releases branch off the master branches.

**Comment by mabod** [comment]
> I've been generally unimpressed by the code quality

But is there any other scheduler you might want to implement in zen instead? BMQ for example? This would help desktop responsiveness quite a bit. Or is your strategy to not touch the scheduler at all?

**Comment by damentz** [comment]
@mabod Zen Kernel is a fork of Linux with early backports and nice out-of-tree features that matter to deskop/laptop users.  Both @heftig's build of `linux-zen` and my build of Liquorix are distributions of Zen Kernel.  Where both our kernels differ is in the configuration.

The Arch `linux-zen` package more closely resembles Arch's primary linux kernel, and only zen specific configuration changes (as far as I'm aware), are configured (@heftig can correct me on that).  Liquorix, on the other hand, has more controversial changes that are configured to get a specific behavior, and are in my opinion, not suitable for wide adoption due to the extra work required to downgrade performance to get power consumption in check for most mobile devices.  Not to mention, Liquorix introduces a higher risk of instability by using MuQSS, but for those that appreciate the improved responsiveness, that risk is worthwhile.

**Comment by mabod** [comment]
Thanks for the clarification. This is good enough for me to close the issue.
