### ISSUE TITLE
zen kernel for LTS

### ISSUE THREAD

**Issue by mabod** [zen-kernel/zen-kernel#196]
Why isnt there a zen kernel for LTS? e.g. for 5.4.88?

**Comment by damentz** [comment]
Frankly, both @heftig and I don't care, we'll never use an LTS branch ourselves and we can't guarantee the quality of a kernel branch we don't dog food.  Not to mention, it's more work, and Zen Kernel still works today because we minimize the amount of work, week-to-week, maintaining our respective distributions.
