### ISSUE TITLE
NVME Remap 

### ISSUE THREAD

**Issue by mithrandir42** [zen-kernel/zen-kernel#224]
Please include support for remapped NVME drives:
https://github.com/endlessm/linux/commit/0922fb63cba0e2bdd95ca2f232afdf3729c3739e 
Thanks!

**Comment by damentz** [comment]
Hi @mithrandir42, do you know if there's intentions to upstream this patch?  Seems a bit invasive, but I understand how valuable it is in that it does fix laptops and desktops configured with "RAID" mode, and maybe other strange boot configurations as mentioned in the patch.

**Comment by mithrandir42** [comment]
Afaik the original patch the patch has been rejected upstream:
https://patchwork.ozlabs.org/project/linux-ide/patch/20190610074456.2761-1-drake@endlessm.com/
https://www.spinics.net/lists/raid/msg63680.html

While trying to install the new computer with this issue I have stumbled upon this patch and reported here, since I am using zen-sources anyways.

**Comment by damentz** [comment]
I see the conflict from linked threads.  Adding this patch allows systems to use drives when in RAID mode in the BIOS.  However, the RAID mode is inefficient and ultimately reduces performance because MSI interrupts are not exposed, which are required to get the full throughput of your installed drive.

Windows is OK with this and works around this by using legacy interrupts when working with the drive in RAID mode.

I think this is worth adding.  Throughput isn't the actual metric that matters, although is frustrating if you're not achieving the full capabilities advertised by the drive for a file storage server.  As long as responsiveness is unaffected, we'll merge this into Zen Kernel, especially if it helps with compatibility of growingly common systems.

**Comment by mithrandir42** [comment]
Thanks! I will try out when setting the machine up and report back with some real world performance measures regarding ahci/raid mode.

**Comment by mithrandir42** [comment]
I have tried out the nvme remapping and did some measures with hdparm ( hdparm -t /dev/nvmeXn ). Results below. We can see, that the remapped devices in rst mode give aproximately 80% of the performance in ahci mode. Most probably due to the interrupt issue. So with Linux rst mode is slower and with Windows (have read somewhere) ahci mode needs more juice. For the time being I will stick to ahci, since Linux is my primary OS. Maybe in the future we can improve performance here.

From the measures we can also see (one drive is slower than the other two, different model), that (at least with my hardware) the ordering of the remapped nvme devices is the other way around in rst mode. For non initrd users this means grub cannot find the root partition (since UUIDs need an initrd image) when switching between ahci and rst mode in bios.

PR fixing this: https://github.com/zen-kernel/zen-kernel/pull/227

-----------------------------------------------------------
ahci mode:
/dev/nvme0n1:
 Timing buffered disk reads: 6278 MB in  3.00 seconds = 2092.26 MB/sec
/dev/nvme1n1:
 Timing buffered disk reads: 8082 MB in  3.00 seconds = 2693.95 MB/sec
/dev/nvme2n1:
 Timing buffered disk reads: 7946 MB in  3.00 seconds = 2648.54 MB/sec

rst mode:
/dev/nvme0n1:
 Timing buffered disk reads: 6566 MB in  3.00 seconds = 2188.13 MB/sec
/dev/nvme1n1:
 Timing buffered disk reads: 6850 MB in  3.00 seconds = 2283.04 MB/sec
/dev/nvme2n1:
 Timing buffered disk reads: 5184 MB in  3.00 seconds = 1727.69 MB/sec
