### ISSUE TITLE
Impossible to clone

### ISSUE THREAD

**Issue by fabrixx** [zen-kernel/zen-kernel#226]
I'm trying to clone from AUR but after 3 GB I exceeded my provider's limit by paying extra data as well. Out of curiosity I would like to know how many GB of space it takes to clone zen-kernel git
![aaaaaaaaa](https://user-images.githubusercontent.com/1190942/126906908-3945b85a-88af-4cd0-a36b-44b7c6031d79.png)

**Comment by damentz** [comment]
The Zen Kernel git repository roughly matches upstream Linux, which is now about 3GB of history.

For shallow clone, git pulls about 200mb:
`Receiving objects: 100% (75922/75922), 202.98 MiB`

For a full clone, git pulls about 3gb:
`Receiving objects: 100% (8496763/8496763), 3.27 GiB`

And for Linus's upstream repository, git pulls 2gb:
`Receiving objects: 100% (8246662/8246662), 2.20 GiB`

Depending on what you're doing, a shallow clone may make more sense, or the automated archives associated with every tag.  But to collaborate and use the full git repository, expect to pull lots of data, often.

One option that may help is to first clone Linus's repository.  Then add Zen Kernel as a remote and run `git fetch`.  This will pull only the difference between Zen Kernel and upstream Linus.

**Comment by damentz** [comment]
And sorry, just to add, looking at your screenshot and reading your post again.  If you are bandwidth starved and limited per day or month, stick to binary builds of `linux-zen`.  Once you're using the AUR you're on your own somewhat.

Maybe you can badger the maintainer of `linux-zen-anbox` to switch to base kernel + patches.  Also, Anbox has been part of `linux-zen` since 5.11 if I remember correctly.
