### ISSUE TITLE
cacule experiment. Why?

### ISSUE THREAD

**Issue by mabod** [zen-kernel/zen-kernel#246]
Why is linux-zen all of a sudden a playground for new CPU schedulers? I thought linux-zen is staying close to the arch kernels. 
I would prefer that you keep it that way and eventually create a linux-zen-cacule branch for those who want to experiment. But I would prefer if you do not mess with the CPU scheduler in the default linux-zen kernel. You should not be forcing a new CPU scheduler on all linux-zen users. Just my 2 cents.

**Comment by heftig** [comment]
ZEN has always been a playground for features, although we tend to be on the conservative side compared to other projects.

I did not use MuQSS for linux-zen as I need group scheduling, which MuQSS does not provide. CacULE did, so was worth a try but this experiment failed.

**Comment by damentz** [comment]
One major requirement of the `linux-zen` build is it must be a drop in replacement for the stock kernel.  That means we can't trade one feature for another (switching to MuQSS disables some cgroup features causes other subtle regressions).

CacULE was a worthwhile experiment since it only changed the behavior of CFS, but it appears to regress abnormally in some use cases as you can see by looking at the issues closed recently.
