### ISSUE TITLE
Fast Headers patchset

### ISSUE THREAD

**Issue by travankor** [zen-kernel/zen-kernel#271]
This patchset doesn't change the kernel functionally, but it does speed up build times, which is useful for everyone compiling their own kernels.

https://lore.kernel.org/lkml/Ydm7ReZWQPrbIugn@gmail.com/

**Comment by damentz** [comment]
Yep, this patch does improve build times, but it's going to break most out-of-tree patches, including probably most DKMS.  Ingo did most of the work for each subsystem maintainer, but the maintainer that loses out here is anyone who's been rebasing patches in their free time outside of mainline.

In-fact, I'm sort of dreading the day this hits mainline since the amount of work required to sync our patches won't be trivial.  I'll pass for now and revisit once we start seeing subsystems merge his changes.
