### ISSUE TITLE
Alternative frequency scallers?

### ISSUE THREAD

**Issue by ghost** [zen-kernel/zen-kernel#276]
Don't take me wrong, schedutil is pretty good for performance(in comparison with fairly battery friendly settings for ondemand) as well as is jitter free and in vast majority of workloads it is on par with performance, while being significantly cooler when it is required.    
I don't experience much stutter even with powersave in desktop tasks.         

But the moment there's a high ratio of kernel module cpu usage(say ultra aggressive zswap settings with 60-90% of ram being provisioned for compressed zswap use and % page threshold being set fairly high), schedutil essentially starts behaving like powersave, further crippling performance.

There's an argument to be had that a compile job with 4c/8t and 12GB of ram and slightly over 16GB peak swap usage is impractical, and that delegating it to a Per Hour/Per Minute/Per Second vps rental or OpenSuse's public build server.

**Comment by kubast2** [comment]
I know I haven't sent over any alternatives, just suggesting an area I feel falls short atm.

**Comment by heftig** [comment]
I assume you're talking about Ryzen specifically?

**Comment by kubast2** [comment]
Yes I've a Ryzen 3 5300U

**Comment by heftig** [comment]
So is this stuttering a problem with `schedutil` specifically? Have you tested `performance` and `ondemand`?

**Comment by kubast2** [comment]
``performance`` works fine, it sets the frequency to ``base freq of 2600mhz`` and from there the turbo gets engaged which is outside of the schedulers control afaik;

I haven't tried ``ondemand`` yet for this workload;

I will need to re-download the rocm sources, or find some alternative like rn I can launch 2-10 THz(and above) resolution of an 44.1khz to 90mhz fm radio transformation;

**Comment by kubast2** [comment]
``Ondemand`` 2.8-3.9 Ghz average core frequency for a single core user time workload with 65% memory pressure and 40-60% cpu usage;

**Comment by damentz** [comment]
I think the issue you're running into is the nature of what happens when off-CPU work happens that causes your core frequencies to scale down in-between work.  When work _needs_ to happen after scaling down, there's a period of time where you get jank while the frequency governor realizes frequency needs to be increased to match load.

You're also mentioning zswap and memory saturation problems.  Under high memory pressure, any action taken by the kernel to free up memory for active processes will cause jank since the running processes need to be frozen while pages are migrated between active memory and swap.  I recommend you add more memory or disable swap and see if that helps.

And last, it seems like you understand that the performance scheduler is ideal.  It basically will run all your cores at the maximum non-boost frequency under no load, but boost as allowed when load is detected on the CPU.  I recommend running performance at all times unless on battery due to the benefits in performance for bursty or unpredictable workloads.
