### ISSUE TITLE
Remove software CTF shutdowns

### ISSUE THREAD

**Issue by road2react** [zen-kernel/zen-kernel#304]
This patch removes shutdown caused by software: https://hst.sh/ufahikadap.patch

Normally, the hardware decides how and when to activate thermal throttling. This isn't needed in software, so it can be removed.

In some laptop models, the hardware is designed to reach 105C (in short bursts), which would cause an unexpected shutdown. The hardware would automatically throttle the clock speed to maintain a stable 100C (± 5C).

See https://bugs.archlinux.org/task/77879 for more details.

**Comment by heftig** [comment]
I'm pretty sure removing emergency shutdowns for everyone because some models are broken would be very bad.

**Comment by Joz3d** [comment]
What do you mean broken?  As road2react stated these certain models are _designed_ to function that way.  Why do you feel that on Linux users should experience "emergency system shutdowns" (which are experienced as random system shutdowns) while Windows users don't under the same circumstances?

**Comment by damentz** [comment]
@Joz3d that is something the driver should handle properly.  Removing critical thermal fault shutdowns for everyone isn't the answer, it's having upstream handle those models correctly so that the edge case hardware doesn't trigger emergency shutdowns unnecessarily.  The last thing we want is a headline saying, _Warning, uninstall Zen Kernel now!  Laptops are burning up and exploding across the earth because of this one small patch!_

Regardless, we can't accept the patch on technical reasons:
1. Author is fake: `From: Example <example@example.com>`
2. Subject is ambiguous and lazy: `Subject: [PATCH] no ctf`
3. No description citing what, why, and links to resources like the AMD GPU issue here: https://gitlab.freedesktop.org/drm/amd/-/issues/1267.  That's not our responsibility to figure out since we'd just be guessing.

**Comment by Joz3d** [comment]
@damentz Thanks for the detailed response.  I don't actually know the submitter of the patch/their merits, just got linked to this thread from same bug reported on different project.

I guess what I don't understand is the difference in functionality vs. Windows' AMD drivers.  I'm not even running edge-case hardware.  I'm on a 6800 XT... why when I run the same app on Windows the card just throttles itself when too hot, but on Linux it shuts down the OS?  You can understand how the layperson would be like "Works on Windows.  Doesn't work on Linux... stick to Windows."
