### ISSUE TITLE
CFS scheduler is getting replaced with EEVDF in Linux kernel 6.6. What would the Zen kernel parameters be?

### ISSUE THREAD

**Issue by igo95862** [zen-kernel/zen-kernel#327]
https://www.phoronix.com/news/Linux-6.6-EEVDF-Merged

Currently the Zen kernel uses the CFS with tweaked settings: https://github.com/zen-kernel/zen-kernel/commit/7de2596b35ac1dbf55fb384f3d668a7315635c0b

It looks like EEVDF removes a bunch of settings: https://lore.kernel.org/lkml/169165145409.27769.15158486372345244495.tip-bot2@tip-bot2/

**Comment by damentz** [comment]
I pushed up 6.6/zen-sauce based on v6.6-rc1 to resolve some of the conflicts before a release is created, the changes ended up being rather trivial.  Only two tweaks were dropped:

1. Migration threshold: Peter adopted our tweak
2. Scheduling latency: Variable was simply dropped since it's not needed

The rest looks fine to me, but I'll spend some more time looking through all the tunable parameters to see if there's anything else that might make sense to change for Zen Kernel.

**Comment by damentz** [comment]
Here's the latest commit (which may become invalid if more changes are needed before v6.6): https://github.com/zen-kernel/zen-kernel/commit/a4637fa9dd74beea10605392a8cd6b596cce9de6

**Comment by damentz** [comment]
Closing since there's nothing left to do here.

**Comment by igo95862** [comment]
@damentz I looked at the [`init/Kconfig`](https://github.com/zen-kernel/zen-kernel/blob/f0d1b5037d24ee5b94bb79b790597ecf6897c447/init/Kconfig#L150C20-L150C20) file and it still talks about "Minimal granularity". However, looking at the [`kernel/sched/fair.c`](https://github.com/zen-kernel/zen-kernel/blob/6.6/main/kernel/sched/fair.c) file minimal granularity is no longer a thing.
