### ISSUE TITLE
Problem with new kernel update

### ISSUE THREAD

**Issue by Chocobonii** [zen-kernel/zen-kernel#328]
after the last update my GPU and CPU started to have performance issues, having the GPU to crash with any game, by the use of it, i know it's not machine problem, because the game works on previous versions of the kernel, and with lts kernel, without any issue, idk which logs to provide, please tell me, so I can fix it

**Comment by damentz** [comment]
Can you reproduce on a stock 6.5 kernel?

**Comment by Chocobonii** [comment]
what do you mean bu stock?

**Comment by damentz** [comment]
I'm not really sure how to clarify further.  Zen Kernel isn't the only kernel on 6.5.  What happens when you try a different 6.5 kernel?

Regardless, your issue is too broad and has no details.  I know you're asking _us_ for what we can ask _you_, but we don't have time that.  There's about 10-20 steps of troubleshooting and diagnosis you could have performed before posting an issue here, but we don't provide tech support and hand holding to this level.

Closing issue out.
