### ISSUE TITLE
Arch Linux 'filesystem' package update overwrites Zen kernel's default `vm.max_map_count` with lower value

### ISSUE THREAD

**Issue by JJwA7VR8** [zen-kernel/zen-kernel#348]
Arch Linux has recently updated the default `vm.max_map_count` value to 1048576 (https://archlinux.org/news/increasing-the-default-vmmax_map_count-value/). 

Zen kernel already sets this to a higher value of `2147483642` (used by SteamOS I believe), but this arch linux change overwrote the zen kernel default value. I reverted this to zen's higher value by commenting out the relevant parameter in `/usr/lib/sysctl.d/10-arch.conf`

However, I wanted to bring this to your attention just in case you need to make any update to avoid zen kernel's value of `2147483642` from being overwritten by arch defaults.

**Comment by heftig** [comment]
I think it's fine; I believe either value is high enough to avoid issues. We could drop the change on the next rebase.

**Comment by damentz** [comment]
> I'm uncomfortable with making the parameter immutable. I'd rather leave ultimate control to userspace.

I understand, but let me make a case here for making this property read only.

1. `max_map_count` is an artificial limit set by kernel developers, indicating if you go over the default, your software is buggy or doing something it shouldn't.
2. In the real world, software takes advantage of this feature (namely Windows game software through Proton), and will crash or behave incorrectly if the `max_map_count` is exceeded.
3. Once you've raised the default of `max_map_count` from 65k to 1 million, what's the difference between 10 or 100 million?  This limit is merely here as a protest or warning to badly written software, or software that exploits it to achieve goals that would not be possible otherwise (again, gaming through Proton)
4. Users of Zen Kernel and its derivatives install the kernel with a promise or hope that some of these problems may go away due to clever adjustments to defaults, of which Zen Kernel does have many we've figured out over time.

In my opinion, by following Valve's lead like we currently do in `zen-sauce`, but then making it immutable with an `#ifdef CONFIG_ZEN_INTERACTIVE`, we make sure that distro specific configs don't override our opinion of what makes a kernel work better for these use cases.

Even though Arch may set an improved default, what about Manjaro, Artix, Endeavour, Reborn, etc?  Also think about Zen derivatives on Debian and Ubuntu where a bad default may get set for other reasons.  This is one of those problems where the happy path may work fine (installing vanilla Arch), but distributions with pathological defaults will make Zen Kernel misbehave in areas we specifically sought out an in-kernel improvement to fix.

Let me know what you think.  Remember, we can always revert the mutability changes it if a real use case comes up that we didn't think of.  But at the moment, I don't see any downsides, and if there are any, they would be in enterprise/business software workloads, something we don't cater to or care about.

**Comment by damentz** [comment]
@heftig another option is to rename or make a duplicate sysctl for read/write.  For example:

 - `vm.max_map_count` set to 0444
 - `vm.max_map_count_rw` set to 0644

The point is just to prevent distribution installed sysctl configs from changing our default, similar to the problems we had with distros installing `mq-deadline` for the IO scheduler.

**Comment by heftig** [comment]
AFAIU the only problematic case is where userspace doesn't set a limit at all, in which case our change would apply. I don't think we need to jump the gun here. We can revisit this when people actually have the distro config actually turns out to be a problem.

**Comment by damentz** [comment]
Ok, I understand that Zen Kernel is primarily an Arch enthusiast kernel, so applying a solution on top of Arch's looks silly.

With that in mind, I'll carry on this patch with the read only sysctl modification in Liquorix (per https://github.com/damentz/liquorix-package/commit/614aa8f74c66998b026d4871ddd851f1295375dd).  If any other kernel maintainers support distributions outside of Arch, they can take my solution if they need or want it.

As for impact, running `sysctl --system` will prompt the output below with the change in place:
```
sysctl: setting key "vm.max_map_count": Operation not permitted
```

Printing contents using `sysctl` works as expected:
```
$ sysctl vm.max_map_count
vm.max_map_count = 2147483642
```

Closing issue out as patch will be removed in `6.9/zen-sauce` as part of rebase.
