### ISSUE TITLE
Would this patch be about the same as --march=native?

### ISSUE THREAD

**Issue by ilikenwf** [zen-kernel/zen-kernel#46]
https://github.com/graysky2/kernel_gcc_patch

Also, I think zen already has uksm support?

**Comment by loxdegio** [comment]
No, It's not the same as --march=native: it enables additional voices in CPU architecture menu in order to increase the granularity for optimizations for specific processors and vendor, and obviously it include also --march=native for who doesn't know what select, but want to optimize his own kernel :)

Second point, no zen-kernel doesn't include UKSM patch, it did some time ago.

However, if you want try those patches both you can try my repo that include a version of zen kernel with them already included.

https://github.com/loxdegio/linux-zenx

I update my repo when I can, but I'm trying to keep it up to date with this one.

**Comment by ilikenwf** [comment]
As it turns out gcc is smart enough to see the proper options with march=native most of the time.
