### ISSUE TITLE
can you include that firmware please - realtek .

### ISSUE THREAD

**Issue by jemadux** [zen-kernel/zen-kernel#84]
i wanna use zen kernel .. on my debian box . i am using debian stable and i want to compile the latest kernel with BFS/BFQ . ok i know about Liquorix kernel.. but it's better for me to optimize the kernel for my machine .

the firmware is https://github.com/lwfinger/rtlwifi_new/
and the isntallation for  ubuntu and debian and fedora are here .https://chirath02.wordpress.com/2016/05/12/installing-realtek-rtl8723be-driver-for-ubuntu-16-04/.

**Comment by damentz** [comment]
Firmware like this should be maintained by your distribution.  Most distribution kernel packages purge the firmware from the kernel in favor for firmware packages.  In fact, a new firmware package just came out for realtek, would you be able to check to see if it has what you need?

https://packages.debian.org/sid/firmware-realtek

Otherwise, I actually would recommend just downloading the firmware and storing it in /lib/firmware.  Although the license looks clean and safe, the firmware already in the kernel is under a vetted license and I don't want an out-of-tree firmware blob getting this repository / project in legal trouble.

Marking this as closed, we don't plan on merging new firmware.  Ask the maintainer of the firmware package for your distribution to include it.
